apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: my-app-namespace
spec:
  selector:
    app: app-pod  # Assurez-vous que cette étiquette correspond à celle de votre Pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
